#!/usr/bin/env python
import argparse

from couchdb import Server
from openag.cli.config import config as cli_config
from openag_brain.commands import update_module_types

if __name__ == '__main__':
    parser = argparse.ArgumentParser(
        description="Update the firmware_module_type records in the database"
    )
    parser.add_argument(
        "-D", "--db_server", help="Address of the database server"
    )
    vals = parser.parse_args()
    db_server = vals.db_server or cli_config["local_server"]["url"]
    server = Server(db_server)
    update_module_types(server)
